### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by coryalder** [Zedenem/UICircularSlider#1]
Hey!

I'm quite interested in using your UICircularSlider in an upcoming project. It's very nice looking, and almost exactly the control I need.

As I understand it, the GPL is incompatible with the iOS App Store... (http://www.zdnet.com/blog/open-source/no-gpl-apps-for-apples-app-store/8046). I wonder if you might consider changing the licence to something more permissive?

All the best,
Cory

**Comment by Zedenem** [comment]
Done.
