### ISSUE TITLE
warn about arc requirement

### ISSUE THREAD

**Issue by ConfusedVorlon** [Zedenem/UICircularSlider#2]
Hi,
I don't use arc, and didn't realise UICircular slider was assuming arc until I hit a crash.

Could you add this warning?
# if ! __has_feature(objc_arc)
# warning This file must be compiled with ARC. Use -fobjc-arc flag (or convert project to ARC).
# endif

**Comment by Zedenem** [comment]
With a big delay for which I am really sorry, ARC requirement is now clearly stated.
PodSpec comes pretty soon also.

Again thank you very much for these suggestions.
