### ISSUE TITLE
podspec

### ISSUE THREAD

**Issue by ConfusedVorlon** [Zedenem/UICircularSlider#3]
It would be great to get UICircularSlider through cocoapods

thanks in advance!

**Comment by Zedenem** [comment]
Hi ConfusedVorlon,

Again, better late than ever, I just requested for UICircularSlider to be added to CocoaPods Specs:
https://github.com/CocoaPods/Specs/pull/7002

Thank you for suggesting it in the first place. I think I'll do that for other controls and libraries in the future.

**Comment by ConfusedVorlon** [comment]
Hi,

thanks for the arc update and the podspec. Mostly, thanks for a useful
control!

cheers,

Rob

On 17 January 2014 14:42, Zouhair Mahieddine notifications@github.comwrote:

> Hi ConfusedVorlon,
> 
> Again, better late than ever, I just requested for UICircularSlider to be
> added to CocoaPods Specs:
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Zedenem/UICircularSlider/issues/3#issuecomment-32610911
> .

## 

Hobbyist Software is a trading name of Hobbyist Software Limited.
Registered office 12 Fraley Rd, Bristol, BS93BS. Registered in England.
Company no:7876492

**Comment by Zedenem** [comment]
My pleasure!

Don't hesitate to ask for improvements or features, or look at some forks that are doing some great stuff beyond my small contribution.
