### ISSUE TITLE
UIControlEventTouchUpInside not being called

### ISSUE THREAD

**Issue by s1ris** [Zedenem/UICircularSlider#6]
This is a great control, being much more smooth and stable than other circular sliders. However, UICircularSlider does not seem to respond to UIControlEventTouchUpInside, making it difficult to determine when the user has finished touching the control. It would be great if your control supported said UIControlEvent, and very helpful as well.

**Comment by Zedenem** [comment]
Hi!

Just pulled this: https://github.com/Zedenem/UICircularSlider/pull/7

Could you have a look at it and tell me if it's what you need?

Basically, I tried to go one step further (® Nostalgia Critic) by also handling the TouchDown and distinguishing TouchUpInside from TouchUpOutside.

All this is, unlike iOS default UISlider, triggered to the thumb image and not the entire UICircularSlider view frame

**Comment by s1ris** [comment]
Thank you, it works perfectly!
